### ISSUE TITLE
ChannelSet Import fails because of XSS Check

### ISSUE THREAD

**Issue by dougblackjr** [ExpressionEngine/Coilpack#10]
Looking to import a channel set from an EE6 site. Getting this error:

`Channel Field: field_label — invalid_xss_check`

![image](https://github.com/ExpressionEngine/Coilpack/assets/6020323/8817b415-e0fc-4134-9dee-62fbda017dd3)

EE7.4.0
Coilpack 1.2.2

I think I ran into this on the front end with another Coilpack project with conflicting CSRF tokens, but not entirely sure this is the same issue.

Let me know how I can help debug this!

**Comment by bryannielsen** [comment]
@dougblackjr would you mind sending me that channel set (privately on Slack DM is fine).  I've seen this error come up before in working on some new Channel Set functionality and I think it may have been data related for me.  I'd just like to check on that before I look at it from the Coilpack side.

**Comment by dougblackjr** [comment]
[ChannelSet.zip](https://github.com/ExpressionEngine/Coilpack/files/14348487/ChannelSet.zip)

@bryannielsen  Here it is!

**Comment by bryannielsen** [comment]
I think there was a validation change on a more recent version of EE because I was able to import this fine with Coilpack on an EE 7.3 install I had but I get the same error as you're seeing on EE 7.4.2

So this doesn't seem like a Coilpack issue, either you have a malicious looking `Channel Field - field_label` in your export or there's an issue with validation on the EE side
